src/app/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

db = SQLAlchemy()

class Usuarios(db.Model, UserMixin):
    __tablename__ = "usuarios"
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(150), nullable=False)
    email = db.Column(db.String(150), nullable=False, unique=True)
    senha = db.Column(db.String(), nullable=False)
    status = db.Column(db.String(), default="ativo")
    role = db.Column(db.String(4), default="user")
    db.relationship("Tarefas", backref="usuario", lazy=True)
    
class Tarefas(db.Model, UserMixin):
    __tablename__ = "tarefas"
    id = db.Column(db.Integer, primary_key=True)
    usuario_id = db.Column(db.Integer, db.ForeignKey("usuarios.id"), nullable=False)
    titulo = db.Column(db.String(150), nullable=False)
    descricao = db.Column(db.String(1000), nullable=False)

src/app/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, PasswordField, TextAreaField
from wtforms.validators import DataRequired, Email, Length, EqualTo

class CadastroForm(FlaskForm):
    nome = StringField("Nome", validators=[DataRequired(message="O nome não pode estar vazio.")])
    email = StringField("E-mail", validators=[DataRequired(message="O e-mail não pode estar vazio."),
                                              Email(message="E-mail inválido.")])
    senha = PasswordField("Senha", validators=[DataRequired(message="A senha não pode estar vazia."),
                                               Length(min=8, message="A senha deve ter no mínimo 8 caracteres.")])
    conf_senha = PasswordField("Confirmar Senha", validators=[DataRequired(message="Senha vazia."),
                                            Length(min=8, message="A senha deve ter no mínimo 8 caracteres."),
                                            EqualTo("senha", message="As senhas não coincidem.")])
    cadastrar = SubmitField("Cadastrar")                                                    
    
class LoginForm(FlaskForm):
    email = StringField("E-mail", validators=[DataRequired(message="O e-mail não pode estar vazio."),
                                              Email(message="E-mail inválido.")])
    senha = PasswordField("Senha", validators=[DataRequired(message="A senha não pode estar vazia."),
                                               Length(min=8, message="A senha deve ter no mínimo 8 caracteres.")])
    login = SubmitField("Login")
    
class TarefaForm(FlaskForm):
    titulo = StringField("Título", validators=[DataRequired(message="O título deve ser escolhido.")])
    descricao = TextAreaField("Descrição", validators=[DataRequired(message="Digite pelo menos alguma coisa na descrição.")])
    salvar = SubmitField("Salvar")
    
class DeleteForm(FlaskForm):
    deletar = SubmitField("Deletar")
    
class EditForm(FlaskForm):
    editar = SubmitField("Editar")

src/app/__init__.py
from flask import Flask
from flask_login import LoginManager
from src.app.models import db, Usuarios
from src.app.config import Config


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    
    db.init_app(app)
    
    # configurando login manager
    lm = LoginManager()
    lm.login_view = "auth.login"
    lm.login_message = "Acesso negado, faça o login para acessar a página."
    lm.login_message_category = "warning"
    
    lm.init_app(app)
    
    @lm.user_loader
    def load_user(id):
        return Usuarios.query.get(int(id))

    # registrando as blueprints

    from src.app.routes.home import home_route
    from src.app.routes.auth import auth_route
    from src.app.routes.user import user_route
    
    app.register_blueprint(home_route)
    app.register_blueprint(auth_route)
    app.register_blueprint(user_route)
    
    return app

src/app/routes/auth.py
from flask import Blueprint, render_template, url_for, redirect, flash
from flask_login import login_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from src.app.models import db, Usuarios
from src.app.forms import LoginForm, CadastroForm

auth_route = Blueprint("auth", __name__, url_prefix="/auth")



@auth_route.route("/cadastro", methods=["GET", "POST"])
def cadastrar():
    form = CadastroForm()
    
    if form.validate_on_submit():
        nome = form.nome.data
        email = form.email.data
        senha = generate_password_hash(form.senha.data)
        
        usuario_existente = Usuarios.query.filter_by(email=email).first()
        
        if not usuario_existente:
            usuario = Usuarios(nome=nome, email=email, senha=senha)
            
            db.session.add(usuario)
            db.session.commit()
            
            flash ("Usuário cadastrado com sucesso.", "success")
            return redirect(url_for("auth.login"))
            
        flash ("Usuário já existe, faça o login", "warning")
        return redirect(url_for("auth.login"))
        
    
    return render_template("cadastro.html", form=form)

@auth_route.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    
    if form.validate_on_submit():
        
        email = form.email.data
        
        usuario = Usuarios.query.filter_by(email=email).first()
        
        if usuario and check_password_hash(usuario.senha, form.senha.data):
            login_user(usuario)
            
            flash ("Usuário logado com sucesso.", "success")
            return redirect(url_for("user.gerenciador_de_tarefas"))
        
        flash ("Usuário não cadastrado.", "danger")
        return redirect(url_for("auth.cadastrar"))
    
    return render_template("login.html", form=form)


@auth_route.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("home.home"))

src/app/routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint("home", __name__)

@home_route.route("/")
def home():
    return render_template("home.html")

src/app/routes/user.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
from src.app.forms import TarefaForm, DeleteForm, EditForm
from src.app.models import db, Tarefas
from src.app.utils.auth_admin import admin_required

user_route = Blueprint("user", __name__)


@user_route.route("/admin")
@admin_required
def admin():
    return "você está na rota de administrador"

@user_route.route("/gerenciador_tarefas", methods=["GET", "POST"])
@login_required
def gerenciador_de_tarefas():
    tarefas = Tarefas.query.filter_by(usuario_id=current_user.id).all()
    form_deletar = DeleteForm()
    form_editar = EditForm()
    return render_template("gerenciador.html", tarefas=tarefas, form_deletar=form_deletar, form_editar=form_editar)

@user_route.route("/add_tarefas", methods=["GET", "POST"])
@login_required
def add_tarefa():
    form = TarefaForm()
    
    if form.validate_on_submit():
        titulo = form.titulo.data
        descricao = form.descricao.data
    
        tarefa = Tarefas(usuario_id=current_user.id, titulo=titulo, descricao=descricao)
        
        db.session.add(tarefa)
        db.session.commit()
        
        flash ("Tarefa adicionada com sucesso", "success")
        return redirect(url_for("user.gerenciador_de_tarefas"))

    return render_template("form_tarefas.html", form=form, action="add_tarefas")

@user_route.route("/<int:id>/deletar", methods=["POST"])
@login_required
def deletar(id):
    try:
        tarefa = Tarefas.query.get(int(id))
    except Exception:
        flash ("Usuário não encontrado.", "danger")
        return redirect(url_for("user.gerenciador_de_tarefas"))
    
    form = DeleteForm()
    
    if form.validate_on_submit():
        db.session.delete(tarefa)
        db.session.commit()
        flash ("Tarefa deletada", "warning")
        
    return redirect(url_for("user.gerenciador_de_tarefas"))

@user_route.route("/<int:id>/editar", methods=["GET", "POST"])
@login_required
def editar(id):
    form = TarefaForm()
    
    if form.validate_on_submit():
        tarefa = Tarefas.query.get(int(id))
        
        
        tarefa.titulo = form.titulo.data
        tarefa.descricao = form.descricao.data
        db.session.commit()
        
        flash ("Tarefa atualizada com sucesso.", "success")
        return redirect(url_for("user.gerenciador_de_tarefas"))    
    
    return render_template("form_tarefas.html", form=form, action=f"{id}/editar")

src/app/templates/base.html
<!doctype html>
<html lang="pt-BR">
    <head>
        <title>{% block title %}{% endblock %}</title>

        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        
        <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css')}}">

        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />

        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">

    </head>

    <body>
        <header>
            <nav
                class="navbar navbar-expand-sm navbar-light bg-light">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/">Gerenciador de tarefas</a>
                    <button
                        class="navbar-toggler d-lg-none"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#collapsibleNavId"
                        aria-controls="collapsibleNavId"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="collapsibleNavId">
                        <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" href="/" aria-current="page">
                                    Home 
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/gerenciador_tarefas">
                                    Gerenciador de tarefas
                                </a>
                            </li>
                            
                    </div>
                            {% if current_user.is_authenticated %}
                                <div class="d-flex">
                                    <p class="me-3">Olá, {{ current_user.nome }}</p>
                                    <div>
                                        <a href="/auth/logout">
                                            logout
                                        </a>
                                    </div>
                                </div>
                            {% endif %}

                            {% if not current_user.is_authenticated %}
                                <div>
                                    <a href="/auth/cadastro" class="btn btn-secondary">
                                        Cadastro
                                    </a>
                                    <a href="/auth/login" class="btn btn-primary mt-2">
                                        Login
                                    </a>
                                </div>
                            {% endif %}
                </div>
            </nav>
            
        </header>
        <main>{% block content %}{% endblock %}</main>
        <footer>
        </footer>

        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

src/app/templates/cadastro.html
{% extends "base.html" %}{% block title %}Cadastro{% endblock %}

{% block content %}

    <form action="/auth/cadastro" method="post">
        {{ form.hidden_tag() }}

        {{ form.nome.label(class="form-label mt-2") }}
        {{ form.nome(class="form-control", required=false) }}
        {% for erro in form.nome.errors %}
            <div class="alert alert-danger alert-dismissible fade show mt-2">
                {{ erro }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        {% endfor %}

        {{ form.email.label(class="form-label mt-2") }}
        {{ form.email(class="form-control", required=false) }}
        {% for erro in form.email.errors %}
            <div class="alert alert-danger alert-dismissible fade show mt-2">
                {{ erro }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        {% endfor %}

        {{ form.senha.label(class="form-label mt-2") }}
        {{ form.senha(class="form-control", required=false) }}
        {% for erro in form.senha.errors %}
            <div class="alert alert-danger alert-dismissible fade show mt-2">
                {{ erro }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        {% endfor %}

        {{ form.conf_senha.label(class="form-label mt-2") }}
        {{ form.conf_senha(class="form-control", required=false) }}
        {% for erro in form.conf_senha.errors %}
            <div class="alert alert-danger alert-dismissible fade show mt-2">
                {{ erro }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        {% endfor %}

        {% with msgs = get_flashed_messages(with_categories=true) %}
            {% if msgs %}
                {% for cat, msg in msgs %}
                    <div class="alert alert-{{ cat }} alert-dismissible fade show mt-2">
                        {{ msg }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {{ form.cadastrar(class="btn btn-primary mt-3") }}

    </form>

{% endblock %}

src/app/templates/form_tarefas.html
{% extends "base.html" %}{% block title %}Página Inicial{% endblock %}

{% block content %}

    <form action="/{{ action }}" method="post">
        {{ form.hidden_tag() }}

        {{ form.titulo.label(class="form-label") }}
        {{ form.titulo(class="form-control", required=false) }}

        {{ form.descricao.label(class="form-label") }}
        {{ form.descricao(class="form-control", required=false, rows=5) }}
        
        <div class="agrupamento-adicionar">
            {{ form.salvar(class="btn btn-primary mt-3")}}
            <a href="/gerenciador_tarefas" class="mt-3">Voltar</a>
        </div>
    
    </form>

{% endblock %}

src/app/templates/gerenciador.html
{% extends "base.html" %}{% block title %}Gerenciador de tarefas{% endblock %}

{% block content %}

    <div class="container">
        <h3>Gerenciador de tarefas</h3>
        {% if tarefas %}

            {% with msgs = get_flashed_messages(with_categories=true) %}
                {% if msgs %}
                    {% for cat, msg in msgs %}
                        <div class="alert alert-{{ cat }} alert-disimissible fade show mt-2">
                            {{ msg }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            <a href="/add_tarefas" class="btn btn-primary">+ Adicionar Tarefa</a>

            {% for tarefa in tarefas %}

                <div class="card mt-3" id="tarefas">
                    <div class="card-body">
                        <h4 class="card-title">{{ tarefa.titulo }}</h4>
                        <p class="card-text">{{ tarefa.descricao }}</p>
                    </div>

                    <div id="container-botoes-card">
                        <form action="{{ url_for('user.deletar', id=tarefa.id)}}" method="post" id="card-botoes">
                            {{ form_deletar.hidden_tag() }}
                            {{ form_deletar.deletar(class="btn btn-danger") }}
                        </form>
                        <form action="{{ url_for('user.editar', id=tarefa.id)}}" method="post" id="card-botoes">
                            {{ form_editar.hidden_tag() }}
                            {{ form_editar.editar(class="btn btn-primary") }}
                        </form>
                    </div>

                </div>

                
            {% endfor %}


        {% else %}
            <p class="text-body-secondary">Nenhuma tarefa encontrada. Crie uma!</p>
            <a href="/add_tarefas" class="btn btn-primary">+ Adicionar Tarefa</a>

            {% with msgs = get_flashed_messages(with_categories=true) %}
                {% if msgs %}
                    {% for cat, msg in msgs %}
                        <div class="alert alert-{{ cat }} alert-disimissible fade show mt-2">
                            {{ msg }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

        {% endif %}

        
    
    </div>

{% endblock %}

src/app/templates/home.html
{% extends "base.html" %}{% block title %}Página Inicial{% endblock %}

{% block content %}

    <div class="container">
        <h3>Seja bem vindo ao seu gerenciador de tarefas pessoal.</h3>
        <p class="text-body-secondary">Organize seu dia a dia com mais eficiência.</p>
    </div>

{% endblock %}

src/app/templates/login.html
{% extends "base.html" %}{% block title %}Login{% endblock %}

{% block content %}

    <form action="/auth/login" method="post">
        {{ form.hidden_tag() }}

        {{ form.email.label(class="form-label mt-2") }}
        {{ form.email(class="form-control", required=false) }}
        {% for erro in form.email.errors %}
            <div class="alert alert-danger alert-dismissible fade show mt-2">
                {{ erro }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        {% endfor %}

        {{ form.senha.label(class="form-label mt-2") }}
        {{ form.senha(class="form-control", required=false) }}
        {% for erro in form.senha.errors %}
            <div class="alert alert-danger alert-dismissible fade show mt-2">
                {{ erro }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        {% endfor %}

        {% with msgs = get_flashed_messages(with_categories=true) %}
            {% if msgs %}
                {% for cat, msg in msgs %}
                    <div class="alert alert-{{ cat }} alert-dismissible fade show mt-2">
                        {{ msg }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {{ form.login(class="btn btn-primary mt-3") }}

    </form>

{% endblock %}